config {
  type: "incremental",
  description: "This table is an example",
         columns:{
             ct_status_dt: "Count of records per status, per day",
             status: "Order status",
             created_at: "Day in which status is counted for"
  },
  assertions: {
    uniqueKey: ["status", "created_at"]
  }
}

WITH a AS (
    SELECT
        status,
        CAST(created_at AS DATE) created_at
    FROM ${ref("orders")}
)

SELECT  
    COUNT(*) ct_status_dt,
    status,
    created_at
    -- ,shipped_at
FROM a 
GROUP BY
  status,
  created_at
  -- ,shipped_at
ORDER BY
  created_at desc, status